
import React, { useState } from 'react';

interface LoginProps {
  onLogin: () => void;
  onSignup: () => void;
}

const Login: React.FC<LoginProps> = ({ onLogin, onSignup }) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onLogin();
  };

  return (
    <div className="flex min-h-screen w-full flex-row bg-background-light dark:bg-background-dark font-display overflow-hidden">
      {/* Left Side: Visual/Hero */}
      <div
        className="hidden lg:flex relative w-1/2 bg-cover bg-center overflow-hidden"
        style={{ backgroundImage: 'url("https://lh3.googleusercontent.com/aida-public/AB6AXuAzvzBAybx5SkQhXAwRqhIuaAu6jI5s3rrFlQalkaPsHl-rMM_n7kmTPsrSDIb3HpxQYun_Uw9zTHU-nHShLp6swz0MSnH53h0696bPSDUHNpEHm9h-3xrGlgbpYhNmGdiZdX3OhpGaBVzzCv3H0IbPdZctV2lpRz0IXKfMoONJ3J2dGQd4fMO9Y3RPOq93xRD35XjPvmANWAkha54zxEths97aKUPyzFM6NZXxlcctjLuPXLjPtOl2EFEokFLYhc1mMAQyeOmcwHs")' }}
      >
        <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-black/20 to-transparent"></div>
        <div className="relative z-10 flex h-full w-full flex-col justify-between p-12">
          <div className="flex justify-start">
            <div className="inline-flex items-center gap-2 rounded-full bg-white/20 px-4 py-2 backdrop-blur-md border border-white/10 shadow-sm">
              <span className="material-symbols-outlined text-primary text-[20px]">auto_awesome</span>
              <span className="text-sm font-medium text-white">Generated by AI</span>
            </div>
          </div>
          <div className="max-w-lg">
            <h1 className="text-4xl font-bold leading-tight text-white tracking-tight mb-4">
              Turn one photo into <br />
              <span className="text-primary">infinite content.</span>
            </h1>
            <p className="text-lg text-white/80 font-medium">
              Create studio-quality product photography and videos in seconds with our Tiffany Blue inspired AI engine.
            </p>
          </div>
        </div>
      </div>

      {/* Right Side: Login Form */}
      <div className="flex flex-1 flex-col justify-center bg-white dark:bg-background-dark px-6 py-12 lg:px-20 xl:px-24">
        <div className="mx-auto w-full max-w-sm">
          <div className="mb-10">
            <div className="flex items-center gap-2 mb-8">
              <div className="h-8 w-8 rounded-lg bg-primary flex items-center justify-center">
                <span className="material-symbols-outlined text-text-main text-[20px]">shopping_bag</span>
              </div>
              <span className="text-xl font-bold text-text-main dark:text-white tracking-tight">EcomAI</span>
            </div>
            <h2 className="text-3xl font-bold leading-9 tracking-tight text-text-main dark:text-white">
              Welcome back
            </h2>
            <p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">
              Please enter your details to sign in.
            </p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label className="block text-sm font-medium leading-6 text-text-main dark:text-white mb-2" htmlFor="email">
                Email address
              </label>
              <input
                id="email"
                name="email"
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="block w-full rounded-lg border-0 py-3.5 text-text-main shadow-sm ring-1 ring-inset ring-slate-200 dark:ring-slate-700 placeholder:text-slate-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6 dark:bg-slate-800 dark:text-white"
                placeholder="name@company.com"
              />
            </div>
            <div>
              <label className="block text-sm font-medium leading-6 text-text-main dark:text-white mb-2" htmlFor="password">
                Password
              </label>
              <input
                id="password"
                name="password"
                type="password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="block w-full rounded-lg border-0 py-3.5 text-text-main shadow-sm ring-1 ring-inset ring-slate-200 dark:ring-slate-700 placeholder:text-slate-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6 dark:bg-slate-800 dark:text-white"
                placeholder="••••••••"
              />
            </div>

            <div className="flex items-center justify-between">
              <div className="flex items-center">
                <input id="remember-me" name="remember-me" type="checkbox" className="h-4 w-4 rounded border-slate-300 text-primary focus:ring-primary" />
                <label className="ml-2 block text-sm text-slate-600 dark:text-slate-400" htmlFor="remember-me">
                  Remember me
                </label>
              </div>
              <div className="text-sm">
                <a className="font-semibold text-primary hover:text-primary-hover" href="#">
                  Forgot password?
                </a>
              </div>
            </div>

            <button
              type="submit"
              className="flex w-full justify-center rounded-lg bg-primary px-3 py-3.5 text-sm font-bold leading-6 text-slate-900 shadow-sm hover:bg-primary-hover transition-colors"
            >
              Sign in
            </button>
          </form>

          <div className="mt-8">
            <div className="relative">
              <div aria-hidden="true" className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-slate-200 dark:border-slate-800"></div>
              </div>
              <div className="relative flex justify-center text-sm font-medium leading-6">
                <span className="bg-white dark:bg-background-dark px-4 text-slate-500">Or continue with</span>
              </div>
            </div>
            <div className="mt-6 grid grid-cols-2 gap-4">
              <button className="flex w-full items-center justify-center gap-3 rounded-lg bg-white dark:bg-slate-800 px-3 py-2.5 text-sm font-semibold text-text-main dark:text-white shadow-sm ring-1 ring-inset ring-slate-300 dark:ring-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
                <svg className="h-5 w-5" viewBox="0 0 24 24">
                  <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4" />
                  <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853" />
                  <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05" />
                  <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335" />
                </svg>
                <span>Google</span>
              </button>
              <button className="flex w-full items-center justify-center gap-3 rounded-lg bg-white dark:bg-slate-800 px-3 py-2.5 text-sm font-semibold text-text-main dark:text-white shadow-sm ring-1 ring-inset ring-slate-300 dark:ring-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
                <span className="material-symbols-outlined text-[#07C160]">chat</span>
                <span>WeChat</span>
              </button>
            </div>
          </div>
          <p className="mt-10 text-center text-sm text-slate-500 dark:text-slate-400">
            Don't have an account? <button className="font-semibold leading-6 text-primary hover:text-primary-hover" onClick={onSignup}>Sign up</button>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Login;
