"""Add indexes to product_packages for performance

Revision ID: 004
Revises: 198a46ecb467
Create Date: 2026-02-12

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '198a46ecb467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Check existing indexes to avoid duplicate creation
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = inspector.get_indexes('product_packages')
    index_names = [idx['name'] for idx in indexes]

    # 创建索引优化查询性能 (AC 5)
    if 'ix_product_packages_created_at' not in index_names:
        op.create_index(
            op.f('ix_product_packages_created_at'),
            'product_packages',
            ['created_at'],
            unique=False
        )

    # ix_product_packages_status 可能已被 003 创建，检查后再创建
    if 'ix_product_packages_status' not in index_names:
        op.create_index(
            op.f('ix_product_packages_status'),
            'product_packages',
            ['status'],
            unique=False
        )

    if 'ix_product_packages_user_id_created_at' not in index_names:
        op.create_index(
            op.f('ix_product_packages_user_id_created_at'),
            'product_packages',
            ['user_id', 'created_at'],
            unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_product_packages_user_id_created_at'), table_name='product_packages')
    op.drop_index(op.f('ix_product_packages_status'), table_name='product_packages')
    op.drop_index(op.f('ix_product_packages_created_at'), table_name='product_packages')

    # ### end Alembic commands ###
