"""Add name to ProductPackage

Revision ID: 198a46ecb467
Revises: 003
Create Date: 2026-02-12 11:35:25.523462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198a46ecb467'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_packages', sa.Column('name', sa.String(length=255), nullable=False, server_default=''))

    # Skip user_id alter if already UUID type (idempotent migration)
    # The column should already be UUID from initial schema
    # op.alter_column('product_packages', 'user_id',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.UUID(),
    #            existing_nullable=False,
    #            postgresql_using='user_id::uuid')

    # Check if index already exists before creating (idempotent migration)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = inspector.get_indexes('product_packages')
    index_names = [idx['name'] for idx in indexes]

    if 'ix_product_packages_user_id' not in index_names:
        op.create_index(op.f('ix_product_packages_user_id'), 'product_packages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_packages_user_id'), table_name='product_packages')
    op.alter_column('product_packages', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('product_packages', 'name')
    # ### end Alembic commands ###
